# Профиль для STDIO режима (по умолчанию)
spring:
  ai:
    mcp:
      server:
        # Информация о сервере
        name: "1C Platform API Server"
        version: "1.0.0"
        description: "MCP сервер для поиска по API платформы 1С Предприятие"
        instructions: "MCP сервер для поиска по API платформы 1С Предприятие. Выполняет поиск по свойствам, методам и типам."
        type: SYNC

        # Возможности сервера
        capabilities:
          tools:
            # Поддержка инструментов
            enabled: true
          resources:
            # Поддержка ресурсов (отключено для простоты)
            enabled: false
          prompts:
            # Поддержка промптов (отключено для простоты)
            enabled: false
  main:
    web-application-type: none
    banner-mode: off

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.web.servlet.DispatcherServletAutoConfiguration
      - org.springframework.boot.autoconfigure.web.reactive.WebFluxAutoConfiguration
# Настройки логирования
logging:
  #  config: classpath:logback-mcp.xml
  # Все остальные настройки логгирования теперь берутся из logback-mcp.xml
  level:
    root: INFO

server:
  port: -1
