# Профиль конфигурации для среды разработки
# Активируется с помощью spring.profiles.active=dev

spring:
  application:
    name: mcp-yaxunit-runner-dev

# Настройки проекта для разработки
project:
  tests_path: "./tests-dev"
  build_timeout: 600000  # 10 минут для разработки
  test_timeout: 1200000  # 20 минут для разработки

# Настройки платформы 1С для разработки
platform:
  version: null
  auto_detect_version: true
  search_paths:
    - "./1cv8-dev"
    - "/opt/1cv8-dev"
    - "/usr/local/1cv8-dev"

# Настройки информационной базы для разработки
information_base:
  connection: "File='./ib-dev';"
  user: "admin"
  password: ""

# Настройки сборки для разработки
build:
  incremental_enabled: true
  hash_storage_size: 1000
  parallel_build: false  # Отключаем для отладки

# Настройки логирования для разработки
logging:
  level: DEBUG
  enable_file_logging: true
  file_path: "./logs/dev.log"

# Настройки сервера для разработки
server:
  port: 8081
  enable_websocket: true
  websocket_path: "/yaxunit-dev"

# Настройки MCP сервера для разработки
mcp:
  server:
    name: "yaxunit-runner-dev"
    version: "1.0.0-dev"
    description: "MCP server for YaXUnit test execution (Development)"

# Настройки CLI для разработки
cli:
  enable: true
  commands:
    run_all: true
    run_list: true
    run_module: true

# Настройки WebSocket для разработки
websocket:
  enabled: true
  path: "/yaxunit-dev"
  max_connections: 10
  idle_timeout: 600000  # 10 минут

# Настройки безопасности для разработки
security:
  enabled: false
  cors:
    allowed_origins: "*"
    allowed_methods: "*"
    allowed_headers: "*"

# Настройки мониторинга для разработки
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Настройки метрик для разработки
metrics:
  enabled: true
  export:
    prometheus:
      enabled: true

# Настройки кэширования для разработки
cache:
  enabled: true
  type: mapdb
  max_size: 1000
  ttl: 1800000  # 30 минут

# Настройки уведомлений для разработки
notifications:
  enabled: false
  webhook_url: null
  email:
    enabled: false

# Настройки отчетов для разработки
reports:
  enabled: true
  format: json
  output_dir: "./reports-dev"
  include_coverage: true
  include_timing: true

# Настройки параллельного выполнения для разработки
parallel:
  enabled: false  # Отключаем для отладки
  max_threads: 1
  queue_size: 10

# Настройки таймаутов для разработки
timeouts:
  connection: 60000      # 1 минута
  read: 120000          # 2 минуты
  write: 120000         # 2 минуты
  process: 600000       # 10 минут

# Настройки резервного копирования для разработки
backup:
  enabled: true
  directory: "./backup-dev"
  max_files: 5
  retention_days: 7

# Настройки разработки
development:
  debug: true
  hot_reload: true
  profile: true 